import React, { createContext, useContext, useState } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.simulator': 'Simula tu Próxima Inversión',
    'nav.investments': 'Mis Inversiones',
    'nav.plots': 'Parcelas',
    
    'nav.admin': 'Administración',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido a tu Dashboard',
    'dashboard.portfolio': 'Tu portafolio',
    'dashboard.portfolioDesc': 'Invierte en el futuro del planeta, cosecha prosperidad',
    'dashboard.newInvestment': 'Nueva Inversión',
    'dashboard.establishedPlants': 'Plantas Establecidas',
    'dashboard.agavesGrowing': 'agaves creciendo para ti',
    'dashboard.totalInvestment': 'Inversión Total',
    'dashboard.investedCapital': 'capital invertido',
    'dashboard.co2Captured': 'CO₂ Secuestrado',
    'dashboard.positiveImpact': 'impacto ambiental positivo',
    'dashboard.nextHarvest': 'Próxima Cosecha',
    'dashboard.totalPlants': 'Total de Plantas',
    'dashboard.estimatedHarvest': 'Próxima Cosecha',
    'dashboard.noActiveInvestments': 'Sin inversiones activas',
    'dashboard.generalProgress': 'Progreso General',
    'dashboard.avgMaturation': 'Estado promedio de maduración',
    'dashboard.avgMaturity': 'madurez promedio',
    'dashboard.progressByInvestment': 'Progreso por Inversión',
    'dashboard.maturationStatus': 'Estado de maduración de tus plantaciones',
    'dashboard.readyForHarvest': '¡Listo para cosecha!',
    'dashboard.startForestJourney': 'Comienza tu Viaje Forestal',
    'dashboard.noInvestmentsDesc': 'Aún no tienes inversiones. ¡Empieza hoy y contribuye al cuidado del medio ambiente mientras generas rendimientos!',
    'dashboard.firstInvestment': 'Mi Primera Inversión',
    'dashboard.requestNewInvestment': 'Solicitar Nueva Inversión',
    'dashboard.newInvestmentDesc': 'Envía una solicitud para una nueva inversión forestal. Nuestro equipo revisará tu solicitud y se pondrá en contacto contigo.',
    'dashboard.fullName': 'Nombre completo',
    'dashboard.phone': 'Teléfono',
    'dashboard.species': 'Especie',
    'dashboard.selectSpecies': 'Selecciona una especie',
    'dashboard.plantCount': 'Cantidad de plantas',
    'dashboard.establishmentYear': 'Año de establecimiento',
    'dashboard.totalInvestmentAmount': 'Inversión total',
    'dashboard.cancel': 'Cancelar',
    'dashboard.sendRequest': 'Enviar Solicitud',
    'dashboard.requestSent': 'Solicitud enviada',
    'dashboard.requestSuccess': 'Tu solicitud de inversión ha sido enviada correctamente',
    
    // Simulator
    'simulator.title': 'Simulador de Inversión Gavé',
    'simulator.description': 'Calcula el retorno de tu inversión en plantaciones de agave para producción de mezcal',
    'simulator.configTitle': 'Configuración de Inversión',
    'simulator.configDesc': 'Ajusta los parámetros para calcular tu inversión',
    'simulator.species': 'Especie de Agave',
    'simulator.selectSpecies': 'Selecciona una especie',
    'simulator.year': 'Año de Establecimiento',
    'simulator.selectYear': 'Selecciona un año',
    'simulator.plants': 'Número de Plantas',
    'simulator.plantsRange': 'Mínimo 1, máximo 1,000 plantas',
    'simulator.weightPerPlant': 'Peso Esperado por Planta',
    'simulator.weightPerPlantUnit': 'kg por planta',
    'simulator.pricePerKg': 'Precio Esperado por Kg de Agave',
    'simulator.pricePerKgUnit': 'por kg',
    'simulator.initialInvestment': 'Inversión Inicial',
    'simulator.finalReturn': 'Retorno Final',
    'simulator.returnDesc': 'Inversión + 65% de utilidades',
    'simulator.netProfit': 'Ganancia Neta',
    'simulator.harvestBreakdown': 'Desglose de Cosecha',
    'simulator.totalWeight': 'Peso total:',
    'simulator.grossValue': 'Valor bruto:',
    'simulator.maturationTime': 'Tiempo de Maduración',
    'simulator.years': 'años',
    'simulator.harvestDate': 'Fecha estimada de cosecha',
    'simulator.environmentalImpact': 'Impacto Ambiental',
    'simulator.carbonCapture': 'Captura de CO₂',
    'simulator.proceed': 'Proceder con esta Inversión',
    'simulator.accessRequired': 'Acceso requerido',
    'simulator.loginRequired': 'Debes iniciar sesión para proceder con la inversión',
    'simulator.requestSent': 'Solicitud enviada',
    'simulator.requestDesc': 'Hemos recibido tu interés en esta inversión. Nos pondremos en contacto contigo pronto.',
    'simulator.requestError': 'No se pudo enviar la solicitud. Intenta nuevamente.',
    
    // Plots
    'plots.title': 'Parcelas de Cultivo',
    'plots.description': 'Información detallada sobre nuestras parcelas de agave en Oaxaca',
    'plots.totalPlots': 'Total Parcelas',
    'plots.totalArea': 'Área Total',
    'plots.totalPlants': 'Total Plantas',
    'plots.available': 'Disponibles',
    'plots.location': 'Ubicación',
    'plots.dronePhotos': 'Fotografías Aéreas',
    'plots.viewOnMap': 'Ver en Mapa',
    
    // Auth
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.name': 'Nombre',
    'auth.signOut': 'Cerrar Sesión',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.signUpSuccess': 'Registro exitoso',
    'auth.checkEmail': 'Por favor verifica tu correo electrónico para completar el registro',
    'auth.resetEmailSent': 'Correo de restablecimiento enviado',
    'auth.checkEmailForReset': 'Revisa tu correo para restablecer tu contraseña',
    'auth.enterEmailFirst': 'Por favor ingresa tu correo electrónico primero',
    'auth.description': 'Accede a tu panel de inversiones',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.noAccess': '¿No tienes acceso?',
    'auth.contactAdmin': 'Contacta al administrador para obtener una cuenta.',
    'auth.orExploreWithoutRegistering': 'o explora sin registrarte',
    'auth.viewDemoButton': 'Ver Dashboard Demo',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.close': 'Cerrar',
    'common.language': 'Idioma',
    'common.spanish': 'Español',
    'common.english': 'English',
    
    
    // Investments 
    'investments.title': 'Mis Inversiones',
    'investments.description': 'Visualiza y rastrea tus inversiones forestales',
    'investments.valuationCalculator': 'Calculadora de Valuación',
    'investments.inputParameters': 'Parámetros de Entrada',
    'investments.estimatedPricePerKg': 'Precio por kg estimado:',
    'investments.weightPerPlant': 'Peso por planta:',
    'investments.yourInvestmentData': 'Datos de tu Inversión',
    'investments.plants': 'Plantas',
    'investments.pricePaidPerPlant': 'Precio pagado/planta',
    'investments.totalInvestment': 'Inversión total',
    'investments.valuationProjection': 'Proyección de Valuación',
    'investments.totalEstimatedWeight': 'Peso total estimado',
    'investments.grossRevenue': 'Ingreso bruto',
    'investments.gaveCommission': 'Comisión Gavé (35% sobre ganancias)',
    'investments.netRevenue': 'Ingreso neto',
    'investments.initialInvestment': 'Inversión inicial',
    'investments.totalProfit': 'Ganancia total',
    'investments.roi': 'ROI',
    'investments.calculatorNote': 'Estos cálculos son estimaciones basadas en condiciones ideales de mercado. Los precios reales pueden variar según la oferta, demanda y calidad del producto al momento de la venta.',
    'investments.co2Captured': 'CO₂ Capturado',
    'investments.currentValue': 'Valor Actual',
    'investments.useSimulator': 'Usar simulador',
    'investments.totalPlants': 'Total de Plantas',
    'investments.analysisTitle': 'Análisis de Inversiones',
    'investments.analysisDescription': 'Distribución detallada de tus inversiones por especies y años de establecimiento',
    'investments.detailedInvestments': 'Inversiones Detalladas',
    'investments.speciesDistribution': 'Distribución por Especies',
    'investments.yearDistribution': 'Distribución por Años de Establecimiento',
    'investments.scientificNameNotAvailable': 'Nombre científico no disponible',
    'investments.active': 'Activa',
    'investments.pending': 'Pendiente',
    'investments.completed': 'Completada',
    'investments.plantationYear': 'Año de Plantación',
    'investments.estimatedHarvest': 'Cosecha Estimada',
    'investments.estimatedWeight': 'Peso Estimado',
    'investments.useSimulatorToEstimate': 'Usar simulador para estimar',
    'investments.co2Capture': 'Captura CO₂',
    'investments.tons': 'tons',
    'investments.yearsToHarvest': 'años para la cosecha',
    'investments.remainingYears': 'años restantes',
    'investments.profitModel': 'Modelo de Ganancia',
    'investments.investorGaveShare': 'Inversionista / Gavé',
    'investments.calculationNote': 'Los cálculos son estimaciones basadas en condiciones promedio de cultivo',
    'investments.platformTitle': 'Plataforma de Inversiones en Agricultura Regenerativa',
    
    // Dashboard translations
    'dashboard.co2Calculation': '¿Cómo se calcula?',
    'dashboard.co2Description': 'Los agaves capturan aproximadamente 12 kg de CO₂ por planta al año. Este cálculo se basa en años transcurridos desde la plantación. Esta captura ayuda a mitigar el cambio climático, purifica el aire y contribuye a la regeneración del suelo.',
    'dashboard.demoMode': 'Modo Demo',
    'dashboard.demoDescription': 'Estás explorando datos ficticios. Para realizar inversiones reales y acceder a todas las funciones,',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.description': 'Mantente al día con las últimas actualizaciones',
    
    // Plots page
    'plots.plotName': 'Nombre de la parcela',
    'plots.area': 'Área',
    'plots.plantsEstablished': 'Plantas establecidas',
    'plots.recentPhotos': 'Fotos recientes',
    'plots.active': 'Activa',
    'plots.hectares': 'hectáreas',
    'plots.protectedLocation': 'Ubicación protegida',
    'plots.viewOnGoogleMaps': 'Ver en Google Maps',
    'plots.speciesEstablished': 'Especies establecidas',
    'plots.harvestProgress': 'Progreso hacia cosecha',
    'plots.nextHarvestEstimate': 'Próxima cosecha estimada',
    'plots.plotLocation': 'Ubicación de la parcela',
    'plots.uploadDronePhoto': 'Subir foto con dron',
    
    // Monitoring translations
    'monitoring.title': 'Sistema de Monitoreo Satelital',
    'monitoring.description': 'Monitoreo en tiempo real de condiciones ambientales y crecimiento de cultivos',
    'monitoring.satelliteMonitoring': 'Monitoreo Satelital',
    'monitoring.vegetationIndices': 'Índices de Vegetación Satelital',
    'monitoring.weatherData': 'Datos Meteorológicos Agromonitoring',
    'monitoring.demo': 'Demo',
    'monitoring.connected': 'Conectado',
    'monitoring.apiActive': 'API Activa',
    'monitoring.area': 'Área',
    'monitoring.hectares': 'hectáreas',
    'monitoring.ndvi': 'NDVI',
    'monitoring.ndviDescription': 'Índice de Vegetación',
    'monitoring.evi': 'EVI',
    'monitoring.eviDescription': 'Índice de Vegetación Mejorado',
    'monitoring.ndwi': 'NDWI',
    'monitoring.ndwiDescription': 'Índice de Agua',
    'monitoring.clouds': 'Nubes',
    'monitoring.cloudsDescription': 'Cobertura de Nubes',
    'monitoring.denseVegetation': 'Vegetación Densa',
    'monitoring.moderateVegetation': 'Vegetación Moderada',
    'monitoring.sparseVegetation': 'Vegetación Escasa',
    'monitoring.noVegetation': 'Suelo/Sin Vegetación',
    'monitoring.ndviInterpretation': 'Interpretación NDVI',
    'monitoring.ndviDense': '≥0.6: Vegetación densa',
    'monitoring.ndviModerate': '0.3-0.6: Moderada',
    'monitoring.ndviSparse': '<0.3: Escasa/Suelo',
    'monitoring.satelliteImage': 'Imagen Satelital (NDVI)',
    'monitoring.temperature': 'Temperatura',
    'monitoring.humidity': 'Humedad',
    'monitoring.wind': 'Viento',
    'monitoring.pressure': 'Presión',
    'monitoring.precipitation': 'Precipitación',
    'monitoring.soilTemp': 'Temp. Suelo',
    'monitoring.soilHumidity': 'Humedad Suelo',
    'monitoring.soilData': 'Datos del Suelo',
    'monitoring.lastUpdate': 'Última actualización',
    'monitoring.connectMonitoring': 'Conectar Monitoreo',
    'monitoring.connecting': 'Conectando...',
    'monitoring.plotsOverview': 'Vista General de Parcelas',
    'monitoring.monitoringCenter': 'Centro de Monitoreo Inteligente',
    'monitoring.systemActive': 'Sistema Activo',
    'monitoring.integratedDescription': 'Monitoreo integral de parcelas con datos satelitales, meteorológicos y alertas en tiempo real',
    'monitoring.updateData': 'Actualizar Datos',
    'monitoring.monitoredPlots': 'Parcelas Monitoreadas',
    'monitoring.realTime': 'En tiempo real',
    'monitoring.activeAlerts': 'Alertas Activas',
    'monitoring.needAttention': 'Requieren atención',
    'monitoring.lastUpdateLabel': 'Última Actualización',
    'monitoring.satelliteData': 'Datos satelitales',
    'monitoring.conditions': 'Condiciones',
    'monitoring.optimal': 'Óptimas',
    'monitoring.favorableWeather': 'Clima favorable',
    'monitoring.satellite': 'Satelital',
    'monitoring.summary': 'Resumen',
    'monitoring.map': 'Mapa',
    'monitoring.weather': 'Clima',
    'monitoring.alerts': 'Alertas',
    'monitoring.forecast7Days': 'Pronóstico 7 Días',
    'monitoring.monthHistory': 'Histórico del Mes',
    'monitoring.avgTemperature': 'Temperatura promedio',
    'monitoring.avgHumidity': 'Humedad promedio',
    'monitoring.totalPrecipitation': 'Precipitación total',
    'monitoring.rainyDays': 'Días con lluvia',
    'monitoring.days': 'días',
    'monitoring.alertConfig': 'Configuración de Alertas',
    'monitoring.highTemperature': 'Temperatura Alta',
    'monitoring.threshold': 'Umbral',
    'monitoring.lowSoilHumidity': 'Humedad del Suelo Baja',
    'monitoring.strongWinds': 'Vientos Fuertes',
    'monitoring.active': 'Activo',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.simulator': 'Simulate your Next Investment',
    'nav.investments': 'My Investments',
    'nav.plots': 'Plots',
    
    'nav.admin': 'Administration',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to your Dashboard',
    'dashboard.portfolio': 'Your portfolio',
    'dashboard.portfolioDesc': 'Invest in the planet\'s future, harvest prosperity',
    'dashboard.newInvestment': 'New Investment',
    'dashboard.establishedPlants': 'Established Plants',
    'dashboard.agavesGrowing': 'agaves growing for you',
    'dashboard.totalInvestment': 'Total Investment',
    'dashboard.investedCapital': 'invested capital',
    'dashboard.co2Captured': 'CO₂ Captured',
    'dashboard.positiveImpact': 'positive environmental impact',
    'dashboard.nextHarvest': 'Next Harvest',
    'dashboard.totalPlants': 'Total Plants',
    'dashboard.estimatedHarvest': 'Next Harvest',
    'dashboard.noActiveInvestments': 'No active investments',
    'dashboard.generalProgress': 'General Progress',
    'dashboard.avgMaturation': 'Average maturation status',
    'dashboard.avgMaturity': 'average maturity',
    'dashboard.progressByInvestment': 'Progress by Investment',
    'dashboard.maturationStatus': 'Maturation status of your plantations',
    'dashboard.readyForHarvest': 'Ready for harvest!',
    'dashboard.startForestJourney': 'Start your Forest Journey',
    'dashboard.noInvestmentsDesc': 'You don\'t have investments yet. Start today and contribute to environmental care while generating returns!',
    'dashboard.firstInvestment': 'My First Investment',
    'dashboard.requestNewInvestment': 'Request New Investment',
    'dashboard.newInvestmentDesc': 'Send a request for a new forest investment. Our team will review your request and contact you.',
    'dashboard.fullName': 'Full name',
    'dashboard.phone': 'Phone',
    'dashboard.species': 'Species',
    'dashboard.selectSpecies': 'Select a species',
    'dashboard.plantCount': 'Number of plants',
    'dashboard.establishmentYear': 'Establishment year',
    'dashboard.totalInvestmentAmount': 'Total investment',
    'dashboard.cancel': 'Cancel',
    'dashboard.sendRequest': 'Send Request',
    'dashboard.requestSent': 'Request sent',
    'dashboard.requestSuccess': 'Your investment request has been sent successfully',
    
    // Simulator
    'simulator.title': 'Gavé Investment Simulator',
    'simulator.description': 'Calculate the return on your agave plantation investment for mezcal production',
    'simulator.configTitle': 'Investment Configuration',
    'simulator.configDesc': 'Adjust parameters to calculate your investment',
    'simulator.species': 'Agave Species',
    'simulator.selectSpecies': 'Select a species',
    'simulator.year': 'Establishment Year',
    'simulator.selectYear': 'Select a year',
    'simulator.plants': 'Number of Plants',
    'simulator.plantsRange': 'Minimum 1, maximum 1,000 plants',
    'simulator.weightPerPlant': 'Expected Weight per Plant',
    'simulator.weightPerPlantUnit': 'kg per plant',
    'simulator.pricePerKg': 'Expected Price per Kg of Agave',
    'simulator.pricePerKgUnit': 'per kg',
    'simulator.initialInvestment': 'Initial Investment',
    'simulator.finalReturn': 'Final Return',
    'simulator.returnDesc': 'Investment + 65% of profits',
    'simulator.netProfit': 'Net Profit',
    'simulator.harvestBreakdown': 'Harvest Breakdown',
    'simulator.totalWeight': 'Total weight:',
    'simulator.grossValue': 'Gross value:',
    'simulator.maturationTime': 'Maturation Time',
    'simulator.years': 'years',
    'simulator.harvestDate': 'Estimated harvest date',
    'simulator.environmentalImpact': 'Environmental Impact',
    'simulator.carbonCapture': 'CO₂ Capture',
    'simulator.proceed': 'Proceed with this Investment',
    'simulator.accessRequired': 'Access required',
    'simulator.loginRequired': 'You must sign in to proceed with the investment',
    'simulator.requestSent': 'Request sent',
    'simulator.requestDesc': 'We have received your interest in this investment. We will contact you soon.',
    'simulator.requestError': 'Could not send request. Please try again.',
    
    // Documents
    'documents.title': 'My Documents',
    'documents.description': 'Documents related to your investments and contracts',
    'documents.contract': 'Contract',
    'documents.report': 'Report',
    'documents.date': 'Date',
    'documents.size': 'Size',
    'documents.type': 'Type',
    'documents.download': 'Download',
    'documents.active': 'Active',
    'documents.pending': 'Pending',
    'documents.noDocuments': 'No documents available',
    'documents.noDocumentsDesc': 'Documents related to your investments will appear here once processed.',
    'documents.info': 'Document Information',
    'documents.infoDesc': 'Everything you need to know about your documents',
    'documents.contractsTitle': 'Purchase Contracts',
    'documents.contractsDesc': 'Legal documents that formalize your plant investment. Generated automatically after each approved purchase.',
    'documents.reportsTitle': 'Annual Reports',
    'documents.reportsDesc': 'Technical and market reports on plot status and growth projections for your plants.',
    
    // Plots
    'plots.title': 'Cultivation Plots',
    'plots.description': 'Detailed information about our agave plots in Oaxaca',
    'plots.totalPlots': 'Total Plots',
    'plots.totalArea': 'Total Area',
    'plots.totalPlants': 'Total Plants',
    'plots.available': 'Available',
    'plots.location': 'Location',
    'plots.dronePhotos': 'Aerial Photos',
    'plots.viewOnMap': 'View on Map',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.signOut': 'Sign Out',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpSuccess': 'Registration successful',
    'auth.checkEmail': 'Please check your email to complete registration',
    'auth.resetEmailSent': 'Reset email sent',
    'auth.checkEmailForReset': 'Check your email to reset your password',
    'auth.enterEmailFirst': 'Please enter your email address first',
    'auth.description': 'Access your investment panel',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.noAccess': 'Don\'t have access?',
    'auth.contactAdmin': 'Contact the administrator to get an account.',
    'auth.orExploreWithoutRegistering': 'or explore without registering',
    'auth.viewDemoButton': 'View Demo Dashboard',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.close': 'Close',
    'common.language': 'Language',
    'common.spanish': 'Español',
    'common.english': 'English',

    
    // Investments 
    'investments.title': 'My Investments',
    'investments.description': 'View and track your forest investments',
    'investments.valuationCalculator': 'Valuation Calculator',
    'investments.inputParameters': 'Input Parameters',
    'investments.estimatedPricePerKg': 'Estimated price per kg:',
    'investments.weightPerPlant': 'Weight per plant:',
    'investments.yourInvestmentData': 'Your Investment Data',
    'investments.plants': 'Plants',
    'investments.pricePaidPerPlant': 'Price paid/plant',
    'investments.totalInvestment': 'Total investment',
    'investments.valuationProjection': 'Valuation Projection',
    'investments.totalEstimatedWeight': 'Total estimated weight',
    'investments.grossRevenue': 'Gross revenue',
    'investments.gaveCommission': 'Gavé Commission (35% on profits)',
    'investments.netRevenue': 'Net revenue',
    'investments.initialInvestment': 'Initial investment',
    'investments.totalProfit': 'Total profit',
    'investments.roi': 'ROI',
    'investments.calculatorNote': 'These calculations are estimates based on ideal market conditions. Actual prices may vary depending on supply, demand and product quality at the time of sale.',
    'investments.co2Captured': 'CO₂ Captured',
    'investments.currentValue': 'Current Value',
    'investments.useSimulator': 'Use simulator',
    'investments.totalPlants': 'Total Plants',
    'investments.analysisTitle': 'Investment Analysis',
    'investments.analysisDescription': 'Detailed breakdown of your investments by species and establishment years',
    'investments.detailedInvestments': 'Detailed Investments',
    'investments.speciesDistribution': 'Distribution by Species',
    'investments.yearDistribution': 'Distribution by Establishment Years',
    'investments.scientificNameNotAvailable': 'Scientific name not available',
    'investments.active': 'Active',
    'investments.pending': 'Pending',
    'investments.completed': 'Completed',
    'investments.plantationYear': 'Plantation Year',
    'investments.estimatedHarvest': 'Estimated Harvest',
    'investments.estimatedWeight': 'Estimated Weight',
    'investments.useSimulatorToEstimate': 'Use simulator to estimate',
    'investments.co2Capture': 'CO₂ Capture',
    'investments.tons': 'tons',
    'investments.yearsToHarvest': 'years to harvest',
    'investments.remainingYears': 'years remaining',
    'investments.profitModel': 'Profit Model',
    'investments.investorGaveShare': 'Investor / Gavé',
    'investments.calculationNote': 'Calculations are estimates based on average growing conditions',
    'investments.platformTitle': 'Regenerative Agriculture Investment Platform',
    
    // Dashboard translations
    'dashboard.co2Calculation': 'How is it calculated?',
    'dashboard.co2Description': 'Agaves capture approximately 12 kg of CO₂ per plant per year. This calculation is based on years elapsed since planting. This capture helps mitigate climate change, purifies the air and contributes to soil regeneration.',
    'dashboard.demoMode': 'Demo Mode',
    'dashboard.demoDescription': 'You are exploring fictional data. To make real investments and access all features,',
    
    // Notifications
    'notifications.title': 'Notifications', 
    'notifications.description': 'Stay up to date with the latest updates',
    
    // Plots page
    'plots.plotName': 'Plot name',
    'plots.area': 'Area',
    'plots.plantsEstablished': 'Plants established',
    'plots.recentPhotos': 'Recent photos', 
    'plots.active': 'Active',
    'plots.hectares': 'hectares',
    'plots.protectedLocation': 'Protected location',
    'plots.viewOnGoogleMaps': 'View on Google Maps',
    'plots.speciesEstablished': 'Species established',
    'plots.harvestProgress': 'Progress to harvest',
    'plots.nextHarvestEstimate': 'Next harvest estimated',
    'plots.plotLocation': 'Plot location',
    'plots.uploadDronePhoto': 'Upload drone photo',
    
    // Monitoring translations
    'monitoring.title': 'Satellite Monitoring System',
    'monitoring.description': 'Real-time monitoring of environmental conditions and crop growth',
    'monitoring.satelliteMonitoring': 'Satellite Monitoring',
    'monitoring.vegetationIndices': 'Satellite Vegetation Indices',
    'monitoring.weatherData': 'Agromonitoring Weather Data',
    'monitoring.demo': 'Demo',
    'monitoring.connected': 'Connected',
    'monitoring.apiActive': 'API Active',
    'monitoring.area': 'Area',
    'monitoring.hectares': 'hectares',
    'monitoring.ndvi': 'NDVI',
    'monitoring.ndviDescription': 'Vegetation Index',
    'monitoring.evi': 'EVI',
    'monitoring.eviDescription': 'Enhanced Vegetation Index',
    'monitoring.ndwi': 'NDWI',
    'monitoring.ndwiDescription': 'Water Index',
    'monitoring.clouds': 'Clouds',
    'monitoring.cloudsDescription': 'Cloud Coverage',
    'monitoring.denseVegetation': 'Dense Vegetation',
    'monitoring.moderateVegetation': 'Moderate Vegetation',
    'monitoring.sparseVegetation': 'Sparse Vegetation',
    'monitoring.noVegetation': 'Soil/No Vegetation',
    'monitoring.ndviInterpretation': 'NDVI Interpretation',
    'monitoring.ndviDense': '≥0.6: Dense vegetation',
    'monitoring.ndviModerate': '0.3-0.6: Moderate',
    'monitoring.ndviSparse': '<0.3: Sparse/Soil',
    'monitoring.satelliteImage': 'Satellite Image (NDVI)',
    'monitoring.temperature': 'Temperature',
    'monitoring.humidity': 'Humidity',
    'monitoring.wind': 'Wind',
    'monitoring.pressure': 'Pressure',
    'monitoring.precipitation': 'Precipitation',
    'monitoring.soilTemp': 'Soil Temp',
    'monitoring.soilHumidity': 'Soil Humidity',
    'monitoring.soilData': 'Soil Data',
    'monitoring.lastUpdate': 'Last update',
    'monitoring.connectMonitoring': 'Connect Monitoring',
    'monitoring.connecting': 'Connecting...',
    'monitoring.plotsOverview': 'Plots Overview',
    'monitoring.monitoringCenter': 'Smart Monitoring Center',
    'monitoring.systemActive': 'System Active',
    'monitoring.integratedDescription': 'Integrated plot monitoring with satellite, weather data and real-time alerts',
    'monitoring.updateData': 'Update Data',
    'monitoring.monitoredPlots': 'Monitored Plots',
    'monitoring.realTime': 'Real time',
    'monitoring.activeAlerts': 'Active Alerts',
    'monitoring.needAttention': 'Need attention',
    'monitoring.lastUpdateLabel': 'Last Update',
    'monitoring.satelliteData': 'Satellite data',
    'monitoring.conditions': 'Conditions',
    'monitoring.optimal': 'Optimal',
    'monitoring.favorableWeather': 'Favorable weather',
    'monitoring.satellite': 'Satellite',
    'monitoring.summary': 'Summary',
    'monitoring.map': 'Map',
    'monitoring.weather': 'Weather',
    'monitoring.alerts': 'Alerts',
    'monitoring.forecast7Days': '7 Day Forecast',
    'monitoring.monthHistory': 'Monthly History',
    'monitoring.avgTemperature': 'Average temperature',
    'monitoring.avgHumidity': 'Average humidity',
    'monitoring.totalPrecipitation': 'Total precipitation',
    'monitoring.rainyDays': 'Rainy days',
    'monitoring.days': 'days',
    'monitoring.alertConfig': 'Alert Configuration',
    'monitoring.highTemperature': 'High Temperature',
    'monitoring.threshold': 'Threshold',
    'monitoring.lowSoilHumidity': 'Low Soil Humidity',
    'monitoring.strongWinds': 'Strong Winds',
    'monitoring.active': 'Active',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get language from localStorage, default to 'es'
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('language') as Language) || 'es';
    }
    return 'es';
  });

  // Save language to localStorage when it changes
  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}