// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsofzhyydgdsamkdkmvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzb2Z6aHl5ZGdkc2Fta2RrbXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjgyMDksImV4cCI6MjA2NzE0NDIwOX0.K8jkXqxNZdDoYBYWw0hvcWH19LFhfFG5bPmviVB-TIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});